#ifndef ASIC_RS_FFI_H
#define ASIC_RS_FFI_H

/* Generated with cbindgen:0.28.0 */

/* Generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque factory handle. Owned by the caller; free with [`asic_rs_factory_free`].
typedef struct AsicFactory AsicFactory;

// Opaque miner handle. Owned by the caller; free with [`asic_rs_miner_free`].
typedef struct AsicMiner AsicMiner;

// Returns the last error message for this thread (borrowed; do not free).
// Valid until the next call into the library on this thread that sets an error.
const char *asic_rs_last_error(void);

// Free a string previously returned by this library.
void asic_rs_free_string(char *s);

// Library (FFI crate) version as a static C string. Do not free.
const char *asic_rs_version(void);

// Underlying asic-rs package version as a newly allocated C string.
// Caller must free with [`asic_rs_free_string`].
char *asic_rs_asic_rs_version(void);

// Create a new empty miner factory.
struct AsicFactory *asic_rs_factory_new(void);

// Create a factory pre-loaded with hosts from a CIDR subnet (e.g. "192.168.1.0/24").
// Returns null on error; see [`asic_rs_last_error`].
struct AsicFactory *asic_rs_factory_from_subnet(const char *subnet);

// Create a factory from an octet-range description (e.g. "192","168","1","1-255").
struct AsicFactory *asic_rs_factory_from_octets(const char *o1,
                                                const char *o2,
                                                const char *o3,
                                                const char *o4);

// Create a factory from a compact range string (e.g. "192.168.1.1-255").
struct AsicFactory *asic_rs_factory_from_range(const char *range);

// Free a factory handle.
void asic_rs_factory_free(struct AsicFactory *factory);

// Append hosts from a CIDR subnet. Returns 0 on success, -1 on error.
int asic_rs_factory_with_subnet(struct AsicFactory *factory, const char *subnet);

// Append hosts from a range string. Returns 0 on success, -1 on error.
int asic_rs_factory_with_range(struct AsicFactory *factory, const char *range);

// Append hosts from octet ranges. Returns 0 on success, -1 on error.
int asic_rs_factory_with_octets(struct AsicFactory *factory,
                                const char *o1,
                                const char *o2,
                                const char *o3,
                                const char *o4);

// Enable or disable the initial port connectivity check.
void asic_rs_factory_set_port_check(struct AsicFactory *factory, bool enabled);

// Set concurrent discovery limit.
void asic_rs_factory_set_concurrent_limit(struct AsicFactory *factory, uintptr_t limit);

// Set identification timeout in seconds.
void asic_rs_factory_set_identification_timeout_secs(struct AsicFactory *factory, uint64_t secs);

// Set connectivity timeout in seconds.
void asic_rs_factory_set_connectivity_timeout_secs(struct AsicFactory *factory, uint64_t secs);

// Set connectivity retries.
void asic_rs_factory_set_connectivity_retries(struct AsicFactory *factory, uint32_t retries);

// Set nofile (RLIMIT_NOFILE) target for large scans.
void asic_rs_factory_set_nofile_limit(struct AsicFactory *factory, uint64_t limit);

// Enable or disable automatic nofile adjustment.
void asic_rs_factory_set_nofile_adjustment(struct AsicFactory *factory, bool enabled);

// Apply adaptive concurrency based on the current host list size.
void asic_rs_factory_set_adaptive_concurrency(struct AsicFactory *factory);

// Number of hosts currently configured for scanning.
int asic_rs_factory_len(const struct AsicFactory *factory);

// Whether the factory has no hosts configured.
bool asic_rs_factory_is_empty(const struct AsicFactory *factory);

// JSON array of configured host IP strings. Free with [`asic_rs_free_string`].
char *asic_rs_factory_hosts_json(const struct AsicFactory *factory);

// Discover and construct a miner at `ip`. Returns null if not found / error.
struct AsicMiner *asic_rs_factory_get_miner(struct AsicFactory *factory, const char *ip);

// Scan a single IP with port pre-check (like scan_miner). Returns null if none.
struct AsicMiner *asic_rs_factory_scan_miner(struct AsicFactory *factory, const char *ip);

// Scan all configured hosts. Returns a JSON array of miner summary objects
// plus an out-list of miner handles via `out_miners` / `out_len`.
//
// On success: allocates `*out_miners` as an array of `*mut AsicMiner` of length
// `*out_len`. Free each miner with [`asic_rs_miner_free`], then free the array
// with [`asic_rs_free_miner_list`].
//
// Returns 0 on success, -1 on error.
int asic_rs_factory_scan(struct AsicFactory *factory,
                         struct AsicMiner ***out_miners,
                         uintptr_t *out_len);

// Free an array of miner pointers returned by [`asic_rs_factory_scan`].
// Does **not** free the individual miners — call [`asic_rs_miner_free`] first.
void asic_rs_free_miner_list(struct AsicMiner **list, uintptr_t len);

// Free a miner handle.
void asic_rs_miner_free(struct AsicMiner *miner);

// IP address as a newly allocated C string. Free with [`asic_rs_free_string`].
char *asic_rs_miner_ip(const struct AsicMiner *miner);

// Device info as JSON. Free with [`asic_rs_free_string`].
char *asic_rs_miner_device_info_json(const struct AsicMiner *miner);

// Human-readable summary: "Make Model (Firmware): IP". Free with free_string.
char *asic_rs_miner_summary(const struct AsicMiner *miner);

bool asic_rs_miner_supports_set_fault_light(const struct AsicMiner *miner);

bool asic_rs_miner_supports_set_power_limit(const struct AsicMiner *miner);

bool asic_rs_miner_supports_restart(const struct AsicMiner *miner);

bool asic_rs_miner_supports_pause(const struct AsicMiner *miner);

bool asic_rs_miner_supports_resume(const struct AsicMiner *miner);

bool asic_rs_miner_supports_pools_config(const struct AsicMiner *miner);

bool asic_rs_miner_supports_upgrade_firmware(const struct AsicMiner *miner);

bool asic_rs_miner_supports_scaling_config(const struct AsicMiner *miner);

bool asic_rs_miner_supports_tuning_config(const struct AsicMiner *miner);

bool asic_rs_miner_supports_fan_config(const struct AsicMiner *miner);

// Set credentials for subsequent privileged operations.
// Returns 0 on success, -1 on error.
int asic_rs_miner_set_auth(struct AsicMiner *miner, const char *username, const char *password);

// Full MinerData as JSON. Free with [`asic_rs_free_string`].
char *asic_rs_miner_get_data_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_mac_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_serial_number_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_hostname_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_api_version_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_firmware_version_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_control_board_version_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_hashboards_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_hashrate_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_expected_hashrate_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_fans_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_psu_fans_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_fluid_temperature_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_wattage_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_tuning_target_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_light_flashing_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_messages_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_uptime_secs_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_is_mining_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_pools_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_pools_config_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_scaling_config_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_tuning_config_json(const struct AsicMiner *miner);

char *asic_rs_miner_get_fan_config_json(const struct AsicMiner *miner);

int asic_rs_miner_set_pools_config_json(const struct AsicMiner *miner, const char *json);

int asic_rs_miner_set_scaling_config_json(const struct AsicMiner *miner, const char *json);

int asic_rs_miner_set_tuning_config_json(const struct AsicMiner *miner,
                                         const char *config_json,
                                         const char *scaling_json);

int asic_rs_miner_set_fan_config_json(const struct AsicMiner *miner, const char *json);

int asic_rs_miner_set_fault_light(const struct AsicMiner *miner, bool fault);

int asic_rs_miner_set_power_limit(const struct AsicMiner *miner, double watts);

int asic_rs_miner_restart(const struct AsicMiner *miner);

// Pause mining. `at_time_secs` < 0 means "now" (None).
int asic_rs_miner_pause(const struct AsicMiner *miner, double at_time_secs);

// Resume mining. `at_time_secs` < 0 means "now" (None).
int asic_rs_miner_resume(const struct AsicMiner *miner, double at_time_secs);

// Upgrade firmware from a local file path. Returns 1/0/-1.
int asic_rs_miner_upgrade_firmware(const struct AsicMiner *miner, const char *path);

#endif  /* ASIC_RS_FFI_H */
