use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = PathBuf::from(&crate_dir).join("include");
    let _ = std::fs::create_dir_all(&out_dir);
    let header = out_dir.join("asic_rs_ffi.h");

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        include_guard: Some("ASIC_RS_FFI_H".to_string()),
        autogen_warning: Some(
            "/* Generated by cbindgen. Do not edit by hand. */".to_string(),
        ),
        include_version: true,
        documentation: true,
        documentation_style: cbindgen::DocumentationStyle::C99,
        style: cbindgen::Style::Both,
        enumeration: cbindgen::EnumConfig {
            prefix_with_name: true,
            ..Default::default()
        },
        ..Default::default()
    };

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(header);
}
